# Generated by Django 4.2.5 on 2024-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_conversationhistory_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('Q', 'question'), ('A', 'answer')], max_length=10),
        ),
    ]
